# Generated by Django 4.2.3 on 2023-07-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamForCompany',
        ),
    ]
