# Generated by Django 4.2.3 on 2023-07-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamOfCompany',
            new_name='TeamMemberOfCompany',
        ),
    ]
