# Generated by Django 4.2.3 on 2023-07-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0004_rename_teamofcompany_teammemberofcompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammemberofcompany',
            options={'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.RemoveField(
            model_name='teammemberofcompany',
            name='linkedn_url',
        ),
    ]
